import path from 'node:path';
import fsp from 'node:fs/promises';
import { CANONICAL_DIRNAME, SPECS_DIRNAME, ensureDir, indexFilePath } from '../core/paths.js';
import { buildGraph } from './graph.js';

/**
 * Builds the generated manifest that maps every artifact id to its canonical
 * model files, projection and derived graph data. It is a lookup cache — never
 * hand-edited, always regenerated by the CLI. Lives under `.sdd/canonical/`
 * (v3): model paths are prefixed `.sdd/canonical/`, projections keep the
 * derived `.sdd/` prefix.
 */
export function buildIndex(artifacts) {
  const graph = buildGraph(artifacts);

  return {
    version: 3,
    sourceOfTruth: 'model',
    generatedAt: new Date().toISOString(),
    artifacts: [...artifacts]
      .sort((a, b) => `${a.kind}:${a.slug}`.localeCompare(`${b.kind}:${b.slug}`))
      .map((artifact) => {
        const progress = graph.progressOf(artifact.slug);
        return {
          kind: artifact.kind,
          id: artifact.id,
          slug: artifact.slug,
          title: artifact.title,
          state: artifact.state,
          meta: `${SPECS_DIRNAME}/${CANONICAL_DIRNAME}/${artifact.model.meta}`,
          body: `${SPECS_DIRNAME}/${CANONICAL_DIRNAME}/${artifact.model.body}`,
          projection: artifact.projection ? `${SPECS_DIRNAME}/${artifact.projection}` : null,
          relations: artifact.relations,
          progress: {
            done: artifact.progress?.done === true,
            children: progress.children,
            completedChildren: progress.completed,
            complete: graph.isComplete(artifact),
          },
          remote: artifact.remote,
        };
      }),
  };
}

export async function writeIndex(cwd, artifacts) {
  const index = buildIndex(artifacts);
  const file = indexFilePath(cwd);
  await ensureDir(path.dirname(file));
  await fsp.writeFile(file, `${JSON.stringify(index, null, 2)}\n`, 'utf8');
  return { file, index };
}

export async function readIndex(cwd) {
  try {
    return JSON.parse(await fsp.readFile(indexFilePath(cwd), 'utf8'));
  } catch {
    return null;
  }
}
